env:
  global:
    - CC_TEST_REPORTER_ID=1e44cf4753e42218ed5f66c7ffaadc22465b8d6811d0fc3d8a87224dffc7185b

language: python
python: 3.8

before_install:
  # make depends on poetry
  - pip install poetry

install:
  - make install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - export SECRET_KEY=MY_SECRET_KEY 
  - make check
  - make test

after_script:  
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
