# Generated by Django 3.1.7 on 2021-02-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_organizer',
            field=models.BooleanField(default=False),
        ),
    ]
